--TABLA CATEGORIA

--FUNCION QUE ME DA LA FECHA ACTUAL PARA LA FECHA DE CREACION DE LA CATEGORIA
CREATE OR REPLACE FUNCTION fechaEquipo()
	RETURNS TRIGGER
AS
$$
BEGIN
	NEW.FECHACREACION := CURRENT_DATE;
	RETURN NEW;
END;
$$
LANGUAGE plpgsql;

--CREACION DE TRIGGER DE FECHA ACTUAL PARA USUARIO
CREATE TRIGGER AUTO_FECHA_INICIAL_USUARIO
BEFORE INSERT ON public.CATEGORIA
FOR EACH ROW 
EXECUTE PROCEDURE fechaEquipo();



